_wandb:
    value:
        cli_version: 0.19.7.dev1
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 9
                - 50
                - 53
                - 55
                - 103
                - 106
            "2":
                - 1
                - 5
                - 9
                - 50
                - 53
                - 55
                - 103
                - 106
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.11.10
            "5": 0.19.7.dev1
            "8":
                - 5
            "12": 0.19.7.dev1
            "13": linux-x86_64
